### ISSUE TITLE
phone number rate limit

### ISSUE THREAD

**Issue by mnwato** [erikm0111/phone-number-extractor#2]
Hi
Can this code exceeds the limit of extracting 200 phone numbers per day?

thanks

**Comment by erikm0111** [comment]
Sure, this code can be executed as many times as you want. But if you use it too many times on the same URL then their rate-limiting policy can block you from trying again.

**Comment by mnwato** [comment]
what do you mean by same URL? 
First, I want to exctract all of ads's URL which are listed in a specified category then crawl each exctacted URL(which contains description, images and phone number) and there is an infinity loop (with a delay) which iterates this routine .

Note:
During this process each URL is unique so there are not the same. 
Do you think there is a problem with this method?

thanks
